language: java
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - docker
install:
  - sudo docker build -t bgppeer . 
  - docker_host=$(ifconfig docker0 | grep 'inet' | cut -d ':' -f2 | awk '{ print $1}')
  - echo $docker_host
script:
  - mvn install -X -f ./pom.xml
  - mvn -P generate-javadoc org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar
