FROM openjdk:8-jre
ARG GIT_REVISION=unknown
LABEL git-revision=$GIT_REVISION    

COPY target/topology-*-shaded.jar /opt/tads/topology.jar
COPY target/examples/log4j2.xml /opt/tads/

WORKDIR /opt/tads

EXPOSE 179 8088

ENTRYPOINT ["java", "-Dlog4j.configurationFile=log4j2.xml", "-jar", "topology.jar"]
